# Generated by Django 4.2.13 on 2024-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics', verbose_name='Profile Picture'),
        ),
    ]
