# Generated by Django 4.2.13 on 2024-09-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_key',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_key',
        ),
    ]
